### ISSUE TITLE
Imput not available on web-interface

### ISSUE THREAD

**Issue by cmer81** [Graylog2/graylog-plugin-twitter#2]
Hello,

I use the latest stable version and I find imput is not avaialble from the web interface,

![Image of Imput]
(http://upload.supreme-elite.fr/images/rWUy.png)

![Image of plugins node]
(http://upload.supreme-elite.fr/images/b6aZu.png)

Version web ==> graylog2-web-0.92.3
Version server ==> graylog2-server-0.92.3

Regards,

**Comment by joschi** [comment]
I'm closing this issue because it's stale by now.
